resources:
  - ../../base
 
#nameSuffix: -production
 
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: backend
    patch: |-
      - op: replace
        path: /metadata/annotations/argocd-image-updater.argoproj.io~1image-list
        value: alyas=ghcr.io/sysadmin29/back-end
      - op: replace
        path: /metadata/annotations/argocd-image-updater.argoproj.io~1alyas.allow-tags
        value: regexp:^v[0-9]+.[0-9]+.[0-9]+$
      - op: replace
        path: /spec/destination/namespace
        value: production
      - op: replace
        path: /spec/source/path
        value: three-tier-application/backend/environments/production