apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: three-tier-application
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - backend-staging.aura.local
      secretName: backend-staging-tls
  rules:
    - host: backend-staging.aura.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service-staging
                port:
                  number: 8000